spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://47.104.192.107:3306/base_data?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: jbt1234
eureka:
  client:
    serviceUrl:
      defaultZone: http://zm:zm19950230@localhost:10000/eureka/
server:
  tomcat:
    basedir: /home/service/manage/temp
#fastdfs 配置
fdfs:
  so-timeout: 1500
  connect-timeout: 600
#  thumb-image:
#    width: 150
#    height: 150
  tracker-list:
    - 10.3.10.173:2212