spring:
  datasource:
    url: jdbc:mysql://47.104.192.107:3306/base_data?useSSL=false&characterEncoding=utf-8
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      username: root
      password: jbt1234
      dataSourceProperties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
      minimum-idle: 5
      maximum-pool-size: 10
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    prefer-ip-address: true
    #eureka显示的地址
    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}
    #服务名调用时
    ip-address: ${eureka.instance.hostname}
  client:
    serviceUrl:
      defaultZone: http://zm:zm19950230@localhost:10000/eureka/
feign:
  client:
    config:
      zm-test-service:
        connectTimeout: 30000
        readTimeout: 30000
#  redis:
#     database: 1
#     host: redis.jbtonline.cn
#     password: D34eE8w2172017
#     port: 6379
#     pool:
#        max-idle: 8
#        min-idle: 0
#        max-active: 8
#        max-wait: -1
